overrides:
  '@types/react': ^19.2.7
  '@types/react-dom': ^19.2.3

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - sharp
  - unrs-resolver

allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  sharp: true
  unrs-resolver: true
